[env:esp32-s3-web-player]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
  earlephilhower/ESP8266Audio
  file://../../

build_flags =
  -D WIFI_SSID=\"tas58xx-web\"
  -D WIFI_PASSWORD=\"tas58xx123\"
  -D TAS58XX_ADDRESS=0x4C
  -D TAS58XX_GPIO_PDN=17
  -D PIN_I2C_SDA=18
  -D PIN_I2C_SCL=8
  -D PIN_I2S_BCLK=11
  -D PIN_I2S_LRCLK=12
  -D PIN_I2S_DOUT=10
  -D PIN_SD_MISO=40
  -D PIN_SD_MOSI=38
  -D PIN_SD_SCK=39
  -D PIN_SD_CS=41

